#!/usr/bin/env python3

###
# Generates build files for the project.
# This file also includes the project configuration,
# such as compiler flags and the object matching status.
#
# Usage:
#   python3 configure.py
#   ninja
#
# Append --help to see available options.
###

import argparse
import sys
from pathlib import Path
from typing import Any, Dict, List

from tools.project import (
    Object,
    ProgressCategory,
    ProjectConfig,
    calculate_progress,
    generate_build,
    is_windows,
)

# Game versions
DEFAULT_VERSION = 0
VERSIONS = [
    "GLLE78",  # 0
]

parser = argparse.ArgumentParser()
parser.add_argument(
    "mode",
    choices=["configure", "progress"],
    default="configure",
    help="script mode (default: configure)",
    nargs="?",
)
parser.add_argument(
    "-v",
    "--version",
    choices=VERSIONS,
    type=str.upper,
    default=VERSIONS[DEFAULT_VERSION],
    help="version to build",
)
parser.add_argument(
    "--build-dir",
    metavar="DIR",
    type=Path,
    default=Path("build"),
    help="base build directory (default: build)",
)
parser.add_argument(
    "--binutils",
    metavar="BINARY",
    type=Path,
    help="path to binutils (optional)",
)
parser.add_argument(
    "--compilers",
    metavar="DIR",
    type=Path,
    help="path to compilers (optional)",
)
parser.add_argument(
    "--map",
    action="store_true",
    help="generate map file(s)",
)
parser.add_argument(
    "--debug",
    action="store_true",
    help="build with debug info (non-matching)",
)
if not is_windows():
    parser.add_argument(
        "--wrapper",
        metavar="BINARY",
        type=Path,
        help="path to wibo or wine (optional)",
    )
parser.add_argument(
    "--dtk",
    metavar="BINARY | DIR",
    type=Path,
    help="path to decomp-toolkit binary or source (optional)",
)
parser.add_argument(
    "--objdiff",
    metavar="BINARY | DIR",
    type=Path,
    help="path to objdiff-cli binary or source (optional)",
)
parser.add_argument(
    "--sjiswrap",
    metavar="EXE",
    type=Path,
    help="path to sjiswrap.exe (optional)",
)
parser.add_argument(
    "--verbose",
    action="store_true",
    help="print verbose output",
)
parser.add_argument(
    "--non-matching",
    dest="non_matching",
    action="store_true",
    help="builds equivalent (but non-matching) or modded objects",
)
parser.add_argument(
    "--no-progress",
    dest="progress",
    action="store_false",
    help="disable progress calculation",
)
args = parser.parse_args()

config = ProjectConfig()
config.version = str(args.version)
version_num = VERSIONS.index(config.version)

# Apply arguments
config.build_dir = args.build_dir
config.dtk_path = args.dtk
config.objdiff_path = args.objdiff
config.binutils_path = args.binutils
config.compilers_path = args.compilers
config.generate_map = args.map
config.non_matching = args.non_matching
config.sjiswrap_path = args.sjiswrap
config.progress = args.progress
if not is_windows():
    config.wrapper = args.wrapper
# Don't build asm unless we're --non-matching
if not config.non_matching:
    config.asm_dir = None

# Tool versions
config.binutils_tag = "2.42-1"
config.compilers_tag = "20240706"
config.dtk_tag = "v1.4.1"
config.objdiff_tag = "v2.7.1"
config.sjiswrap_tag = "v1.2.0"
config.wibo_tag = "0.6.11"

# Project
config.config_path = Path("config") / config.version / "config.yml"
config.check_sha_path = Path("config") / config.version / "build.sha1"
config.asflags = [
    "-mgekko",
    "--strip-local-absolute",
    "-I include",
    f"-I build/{config.version}/include",
    f"--defsym BUILD_VERSION={version_num}",
    f"--defsym VERSION_{config.version}",
]
config.ldflags = [
    "-fp hardware",
    "-nodefaults",
]
if args.debug:
    config.ldflags.append("-g")  # Or -gdwarf-2 for Wii linkers
if args.map:
    config.ldflags.append("-mapunused")
    # config.ldflags.append("-listclosure") # For Wii linkers

# Use for any additional files that should cause a re-configure when modified
config.reconfig_deps = []

# Optional numeric ID for decomp.me preset
# Can be overridden in libraries or objects
config.scratch_preset_id = None

# Base flags, common to most GC/Wii games.
# Generally leave untouched, with overrides added below.
cflags_base = [
    "-nodefaults",
    "-proc gekko",
    "-align powerpc",
    "-enum int",
    "-fp hardware",
    "-Cpp_exceptions off",
    # "-W all",
    "-inline auto",
    '-pragma "cats off"',
    '-pragma "warn_notinlined off"',
    "-maxerrors 1",
    "-nosyspath",
    "-RTTI off",
    "-fp_contract on",
    "-str reuse",
    "-multibyte",  # For Wii compilers, replace with `-enc SJIS`
    f"-i build/{config.version}/include",
    f"-DBUILD_VERSION={version_num}",
    f"-DVERSION_{config.version}",
]

cflags_rat_base = [
    *cflags_base,
    "-pool off",
    "-schedule on",
    "-str reuse,pool,readonly",
    "-fp fmadd",
    "-use_lmw_stmw on",
    '-pragma "cpp_extensions on"',
    "-sym on",
    "-inline off",
    "-opt level=4, peep, space",
    "-sdata 32",
    "-sdata2 32",
    "-i src/Engine/includes",
    "-i src/sdk/includes",
    "-O4,p"
]

# Debug flags
if args.debug:
    # Or -sym dwarf-2 for Wii compilers
    cflags_base.extend(["-sym on", "-DDEBUG=1"])
else:
    cflags_base.append("-DNDEBUG=1")

# Metrowerks library flags
cflags_runtime = [
    *cflags_base,
    "-use_lmw_stmw on",
    "-str reuse,pool,readonly",
    "-gccinc",
    "-common off",
    "-inline auto",
    "-O4,p",
]

# REL flags
cflags_rel = [
    *cflags_base,
    "-sdata 0",
    "-sdata2 0",
]

config.linker_version = "GC/2.7"


# Helper function for Dolphin libraries
def DolphinLib(lib_name: str, objects: List[Object]) -> Dict[str, Any]:
    return {
        "lib": lib_name,
        "mw_version": "GC/1.2.5n",
        "cflags": cflags_base,
        "progress_category": "sdk",
        "objects": objects,
    }


# Helper function for REL script objects
def Rel(lib_name: str, objects: List[Object]) -> Dict[str, Any]:
    return {
        "lib": lib_name,
        "mw_version": "GC/1.3.2",
        "cflags": cflags_rel,
        "progress_category": "game",
        "objects": objects,
    }


Matching = True                   # Object matches and should be linked
NonMatching = False               # Object does not match and should not be linked
Equivalent = config.non_matching  # Object should be linked when configured with --non-matching


# Object is only matching for specific versions
def MatchingFor(*versions):
    return config.version in versions


config.warn_missing_config = True
config.warn_missing_source = False
config.libs = [
    {
        "lib": "Runtime.PPCEABI.H",
        "mw_version": config.linker_version,
        "cflags": cflags_base,
        "progress_category": "sdk",  # str | List[str]
        "objects": [
            Object(NonMatching, "serpoll.c"),
            Object(NonMatching, "GXTexture.c"),
            Object(NonMatching, "SIBios.c"),
            Object(NonMatching, "GXGeometry.c"),
            Object(NonMatching, "AXAux.c"),
            Object(NonMatching, "nubinit.c"),
            Object(NonMatching, "dolphin_trk_glue.c"),
            Object(NonMatching, "bink/src/sdk/fft.c"),
            Object(NonMatching, "GXBump.c"),
            Object(NonMatching, "dolphin_trk.c"),
            Object(NonMatching, "abort_exit.c"),
            Object(NonMatching, "mem_TRK.c"),
            Object(NonMatching, "OSMutex.c"),
            Object(NonMatching, "CARDRdwr.c"),
            Object(NonMatching, "e_exp.c"),
            Object(NonMatching, "strtold.c"),
            Object(NonMatching, "MWTrace.c"),
            Object(NonMatching, "GXDisplayList.c"),
            Object(NonMatching, "ptmf.c"),
            Object(NonMatching, "DSPCode.c"),
            Object(NonMatching, "msghndlr.c"),
            Object(NonMatching, "s_floor.c"),
            Object(NonMatching, "rand.c"),
            Object(NonMatching, "OSReboot.c"),
            Object(NonMatching, "CARDStat.c"),
            Object(NonMatching, "strtoul.c"),
            Object(NonMatching, "OSRtc.c"),
            Object(NonMatching, "__start.c"),
            Object(NonMatching, "w_log.c"),
            Object(NonMatching, "Padclamp.c"),
            Object(NonMatching, "Pad.c"),
            Object(NonMatching, "GXInit.c"),
            Object(NonMatching, "bink/src/sdk/dummy.c"),
            Object(NonMatching, "bink/src/sdk/decode/ngc/ngcfile.c"),
            Object(NonMatching, "OSError.c"),
            Object(NonMatching, "dvderror.c"),
            Object(NonMatching, "OSExec.c"),
            Object(NonMatching, "CARDBios.c"),
            Object(NonMatching, "dvdidutils.c"),
            Object(NonMatching, "shared/time/ngc/radcb.c"),
            Object(NonMatching, "__init_cpp_exceptions.cpp"),
            Object(NonMatching, "nubevent.c"),
            Object(NonMatching, "uart_console_io_gcn.c"),
            Object(NonMatching, "OSCache.c"),
            Object(NonMatching, "GXFifo.c"),
            Object(NonMatching, "mtx.c"),
            Object(NonMatching, "msg.c"),
            Object(NonMatching, "bink/src/sdk/decode/ngc/ngcsnd.c"),
            Object(NonMatching, "CARDCreate.c"),
            Object(NonMatching, "buffer_io.c"),
            Object(NonMatching, "CARDBlock.c"),
            Object(NonMatching, "locale.c"),
            Object(NonMatching, "extras.c"),
            Object(NonMatching, "e_rem_pio2.c"),
            Object(NonMatching, "OSAlarm.c"),
            Object(NonMatching, "OSArena.c"),
            Object(NonMatching, "e_acos.c"),
            Object(NonMatching, "OSFont.c"),
            Object(NonMatching, "AXVPB.c"),
            Object(NonMatching, "OSLink.c"),
            Object(NonMatching, "ansi_fp.c"),
            Object(NonMatching, "GXTransform.c"),
            Object(NonMatching, "msgbuf.c"),
            Object(NonMatching, "ar.c"),
            Object(NonMatching, "s_frexp.c"),
            Object(NonMatching, "OSMemory.c"),
            Object(NonMatching, "mem.c"),
            Object(NonMatching, "k_sin.c"),
            Object(NonMatching, "dispatch.c"),
            Object(NonMatching, "CARDDelete.c"),
            Object(NonMatching, "mem_funcs.c"),
            Object(NonMatching, "flush_cache.c"),
            Object(NonMatching, "db.c"),
            Object(NonMatching, "CARDOpen.c"),
            Object(NonMatching, "PPCArch.c"),
            Object(NonMatching, "AX.c"),
            Object(NonMatching, "CARDUnlock.c"),
            Object(NonMatching, "mtx44.c"),
            Object(NonMatching, "dsp_debug.c"),
            Object(NonMatching, "notify.c"),
            Object(NonMatching, "s_modf.c"),
            Object(NonMatching, "OS.c"),
            Object(NonMatching, "wchar_io.c"),
            Object(NonMatching, "alloc.c"),
            Object(NonMatching, "mpc_7xx_603e.c"),
            Object(NonMatching, "arq.c"),
            Object(NonMatching, "bink/src/sdk/decode/binkacd.c"),
            Object(NonMatching, "s_sin.c"),
            Object(NonMatching, "w_sqrt.c"),
            Object(NonMatching, "misc_io.c"),
            Object(NonMatching, "mutex_TRK.c"),
            Object(NonMatching, "target_options.c"),
            Object(NonMatching, "GXMisc.c"),
            Object(NonMatching, "MWCriticalSection_gc.cpp"),
            Object(NonMatching, "main.c"),
            Object(NonMatching, "DupeCDir/main.c_1"),
            Object(NonMatching, "k_cos.c"),
            Object(NonMatching, "qsort.c"),
            Object(NonMatching, "dvdFatal.c"),
            Object(NonMatching, "critical_regions.gamecube.c"),
            Object(NonMatching, "CARDRead.c"),
            Object(NonMatching, "dvd.c"),
            Object(NonMatching, "dvdqueue.c"),
            Object(NonMatching, "CARDMount.c"),
            Object(NonMatching, "dvdfs.c"),
            Object(NonMatching, "k_rem_pio2.c"),
            Object(NonMatching, "OSContext.c"),
            Object(NonMatching, "usr_put.c"),
            Object(NonMatching, "s_atan.c"),
            Object(NonMatching, "CARDNet.c"),
            Object(NonMatching, "AXProf.c"),
            Object(NonMatching, "OSResetSW.c"),
            Object(NonMatching, "AXAlloc.c"),
            Object(NonMatching, "__mem.c"),
            Object(NonMatching, "targcont.c"),
            Object(NonMatching, "GXPixel.c"),
            Object(NonMatching, "OSSync.c"),
            Object(NonMatching, "s_cos.c"),
            Object(NonMatching, "mslsupp.c"),
            Object(NonMatching, "s_ldexp.c"),
            Object(NonMatching, "GXPerf.c"),
            Object(NonMatching, "OSAudioSystem.c"),
            Object(NonMatching, "w_atan2.c"),
            Object(NonMatching, "SISamplingRate.c"),
            Object(NonMatching, "dsp.c"),
            Object(NonMatching, "odenotstub.c"),
            Object(NonMatching, "CARDDir.c"),
            Object(NonMatching, "e_atan2.c"),
            Object(NonMatching, "string.c"),
            Object(NonMatching, "OSReset.c"),
            Object(NonMatching, "GXFrameBuf.c"),
            Object(NonMatching, "errno.c"),
            Object(NonMatching, "bink/src/sdk/decode/expand.c"),
            Object(NonMatching, "ai.c"),
            Object(NonMatching, "ansi_files.c"),
            Object(NonMatching, "w_exp.c"),
            Object(NonMatching, "FILE_POS.C"),
            Object(NonMatching, "bink/src/sdk/decode/ppc/ppcyuy2.c"),
            Object(NonMatching, "NMWException.cp"),
            Object(NonMatching, "bink/src/sdk/decode/yuv.c"),
            Object(NonMatching, "fstload.c"),
            Object(NonMatching, "texPalette.c"),
            Object(NonMatching, "EXIBios.c"),
            Object(NonMatching, "main_TRK.c"),
            Object(NonMatching, "math_ppc.c"),
            Object(NonMatching, "UDP_Stubs.c"),
            Object(NonMatching, "AXCL.c"),
            Object(NonMatching, "AmcExi2Stubs.c"),
            Object(NonMatching, "AXOut.c"),
            Object(NonMatching, "CPlusLibPPC.cp"),
            Object(NonMatching, "w_acos.c"),
            Object(NonMatching, "targimpl.c"),
            Object(NonMatching, "float.c"),
            Object(NonMatching, "mix.c"),
            Object(NonMatching, "bink/src/sdk/decode/binkread.c"),
            Object(NonMatching, "CARDWrite.c"),
            Object(NonMatching, "e_sqrt.c"),
            Object(NonMatching, "CARDFormat.c"),
            Object(NonMatching, "EXIUart.c"),
            Object(NonMatching, "direct_io.c"),
            Object(NonMatching, "w_pow.c"),
            Object(NonMatching, "bink/src/sdk/bitplane.c"),
            Object(NonMatching, "ctype.c"),
            Object(NonMatching, "Gecko_ExceptionPPC.cp"),
            Object(NonMatching, "printf.c"),
            Object(NonMatching, "bink/src/sdk/dct.c"),
            Object(NonMatching, "InGameDatas_Z.cpp"),
            Object(NonMatching, "support.c"),
            Object(NonMatching, "e_pow.c"),
            Object(NonMatching, "mainloop.c"),
            Object(NonMatching, "GXTev.c"),
            Object(NonMatching, "s_ceil.c"),
            Object(NonMatching, "shared/memory/ngc/radmem.c"),
            Object(NonMatching, "GXAttr.c"),
            Object(NonMatching, "runtime.c"),
            Object(NonMatching, "CARDCheck.c"),
            Object(NonMatching, "bink/src/sdk/decode/ngc/binkngc.c"),
            Object(NonMatching, "DebuggerDriver.c"),
            Object(NonMatching, "bink/src/sdk/popmal.c"),
            Object(NonMatching, "__ppc_eabi_init.cpp"),
            Object(NonMatching, "mbstring.c"),
            Object(NonMatching, "s_copysign.c"),
            Object(NonMatching, "OSInterrupt.c"),
            Object(NonMatching, "__va_arg.c"),
            Object(NonMatching, "vi.c"),
            Object(NonMatching, "OSTime.c"),
            Object(NonMatching, "dsp_task.c"),
            Object(NonMatching, "OSThread.c"),
            Object(NonMatching, "dvdlow.c"),
            Object(NonMatching, "AXComp.c"),
            Object(NonMatching, "OSAlloc.c"),
            Object(NonMatching, "scanf.c"),
            Object(NonMatching, "CircleBuffer.c"),
            Object(NonMatching, "file_io.c"),
            Object(NonMatching, "global_destructor_chain.c"),
            Object(NonMatching, "e_log.c"),
            Object(NonMatching, "GXLight.c"),
            Object(NonMatching, "AXSPB.c"),
            Object(NonMatching, "targsupp.s"),
            Object(NonMatching, "__exception.s"),
        ],
    },
    {
        "lib": "Engine",
        "mw_version": config.linker_version,
        "cflags": cflags_rat_base,
        "progress_category": "engine",  # str | List[str]
        "objects": [
            Object(NonMatching, "Engine/ObjectBankManager_Z.cpp"),
            Object(NonMatching, "Engine/GameManager_Z.cpp"),
            Object(NonMatching, "Engine/Math_Z.cpp"),
            Object(NonMatching, "Engine/ObjectsMoveCollShadow_Z.cpp"),
            Object(NonMatching, "Engine/InGameObjects_Z.cpp"),
            Object(NonMatching, "Engine/SuperSprayEle_Z.cpp"),
            Object(NonMatching, "Engine/GameSub_Z.cpp"),
            Object(NonMatching, "Engine/StreamFile_Z.cpp"),
            Object(NonMatching, "Engine/LodMoveColl_Z.cpp"),
            Object(NonMatching, "Engine/LodMove_Z.cpp"),
            Object(NonMatching, "Engine/LodAgent_Z.cpp"),
            Object(NonMatching, "Engine/CameraZoneLoad_Z.cpp"),
            Object(NonMatching, "Engine/Txt_Z.cpp"),
            Object(NonMatching, "Engine/PointsLoad_Z.cpp"),
            Object(NonMatching, "Engine/Menu3DLoadAscii_Z.cpp"),
            Object(NonMatching, "Engine/LodShadow_Z.cpp"),
            Object(NonMatching, "Engine/Surface_Z.cpp"),
            Object(NonMatching, "Engine/ObjectMoveColl_Z.cpp"),
            Object(NonMatching, "Engine/SurfaceCollision_Z.cpp"),
            Object(NonMatching, "Engine/GameSubData_Z.cpp"),
            Object(NonMatching, "Engine/CollisionVolDraw_Z.cpp"),
            Object(NonMatching, "Engine/ParticlesAgent_Z.cpp"),
            Object(NonMatching, "Engine/CameraEngineZoneCapture_Z.cpp"),
            Object(NonMatching, "Engine/VolatileMem_Z.cpp"),
            Object(NonMatching, "Engine/ObjectsGameClip_Z.cpp"),
            Object(NonMatching, "Engine/MeshLoad_Z.cpp"),
            Object(NonMatching, "Engine/CameraZoneDraw_Z.cpp"),
            Object(NonMatching, "Engine/Movie_Z.cpp"),
            Object(NonMatching, "Engine/SurfaceCollisionSphere_Z.cpp"),
            Object(NonMatching, "Engine/Viewport_Z.cpp"),
            Object(NonMatching, "Engine/ABC_Agent.cpp"),
            Object(NonMatching, "Engine/WorldLightning_Z.cpp"),
            Object(NonMatching, "Engine/HFog_Z.cpp"),
            Object(NonMatching, "Engine/AnimationMaterial_Z.cpp"),
            Object(NonMatching, "Engine/AnimationMorph_Z.cpp"),
            Object(NonMatching, "Engine/MathTools_Z.cpp"),
            Object(NonMatching, "Engine/Manipulator_Z.cpp"),
            Object(NonMatching, "Engine/Parameters_Z.cpp"),
            Object(NonMatching, "Engine/MovieManipulator_Z.cpp"),
            Object(NonMatching, "Engine/Language_Z.cpp"),
            Object(NonMatching, "Engine/SkelLoad_Z.cpp"),
            Object(NonMatching, "Engine/Emiter_Z.cpp"),
            Object(NonMatching, "Engine/ErrorLanguage_Z.cpp"),
            Object(NonMatching, "Engine/RotShapeLoad_Z.cpp"),
            Object(NonMatching, "Engine/ObjectsBounce_Z.cpp"),
            Object(NonMatching, "Engine/LodDraw_Z.cpp"),
            Object(NonMatching, "Engine/WorldAnim_Z.cpp"),
            Object(NonMatching, "Engine/LightDraw_Z.cpp"),
            Object(NonMatching, "Engine/Gaussian_Z.cpp"),
            Object(NonMatching, "Engine/EffectManager_Z.cpp"),
            Object(NonMatching, "Engine/SurfaceCollisionCapsule_Z.cpp"),
            Object(NonMatching, "Engine/CameraUser_Z.cpp"),
            Object(NonMatching, "Engine/ParticlesEle_Z.cpp"),
            Object(NonMatching, "Engine/ConsoleCommand_Z.cpp"),
            Object(NonMatching, "Engine/Menu3D_Z.cpp"),
            Object(NonMatching, "Engine/Pack_Z.cpp"),
            Object(NonMatching, "Engine/Occluder_Z.cpp"),
            Object(NonMatching, "Engine/SurfaceCollisionTools_Z.cpp"),
            Object(NonMatching, "Engine/BaseObject_Z.cpp"),
            Object(NonMatching, "Engine/EmiterCollision_Z.cpp"),
            Object(NonMatching, "Engine/KeyframerFloat_Z.cpp"),
            Object(NonMatching, "Engine/GraphVertex_Z.cpp"),
            Object(NonMatching, "Engine/Memory_Z.cpp"),
            Object(NonMatching, "Engine/GameManipulators_Z.cpp"),
            Object(NonMatching, "Engine/Warp_Z.cpp"),
            Object(NonMatching, "Engine/InGameObjectsManipulator_Z.cpp"),
            Object(NonMatching, "Engine/SplineLoad_Z.cpp"),
            Object(NonMatching, "Engine/DynamicAnim_Z.cpp"),
            Object(NonMatching, "Engine/InGameDatasDraw_Z.cpp"),
            Object(NonMatching, "Engine/MeshCollisionMovingSphere.cpp"),
            Object(NonMatching, "Engine/SkinDraw_Z.cpp"),
            Object(NonMatching, "Engine/OccluderDraw_Z.cpp"),
            Object(NonMatching, "Engine/SystemObject_Z.cpp"),
            Object(NonMatching, "Engine/ObjectsBreak_Z.cpp"),
            Object(NonMatching, "Engine/OmniDraw_Z.cpp"),
            Object(NonMatching, "Engine/Frustrum_Z.cpp"),
            Object(NonMatching, "Engine/WorldCollision_Z.cpp"),
            Object(NonMatching, "Engine/LodLighting_Z.cpp"),
            Object(NonMatching, "Engine/MovingAgent_Z.cpp"),
            Object(NonMatching, "Engine/MeshCollisionCapsule_Z.cpp"),
            Object(NonMatching, "Engine/GameStream_Z.cpp"),
            Object(NonMatching, "Engine/Points_Z.cpp"),
            Object(NonMatching, "Engine/GameManagerRtc_Z.cpp"),
            Object(NonMatching, "Engine/SkinCollision_Z.cpp"),
            Object(NonMatching, "Engine/MatrixCache_Z.cpp"),
            Object(NonMatching, "Engine/SurfaceCache_Z.cpp"),
            Object(NonMatching, "Engine/ABC_Category.cpp"),
            Object(NonMatching, "Engine/AnimatedMsgAgent_Z.cpp"),
            Object(NonMatching, "Engine/StreamAgent_Z.cpp"),
            Object(NonMatching, "Engine/ObjectMoveCollShadow_Z.cpp"),
            Object(NonMatching, "Engine/SystemDatas_Z.cpp"),
            Object(NonMatching, "Engine/ParticlesLoad_Z.cpp"),
            Object(NonMatching, "Engine/SkinAgent_Z.cpp"),
            Object(NonMatching, "Engine/MeshCollision_Z.cpp"),
            Object(NonMatching, "Engine/CameraAgent_Z.cpp"),
            Object(NonMatching, "Engine/InputEngine_Z.cpp"),
            Object(NonMatching, "Engine/KSys_Z.cpp"),
            Object(NonMatching, "Engine/SplineDraw_Z.cpp"),
            Object(NonMatching, "Engine/LowLevelTools_Z.cpp"),
            Object(NonMatching, "Engine/BitmapLoad_Z.cpp"),
            Object(NonMatching, "Engine/Game_Z.cpp"),
            Object(NonMatching, "Engine/ObjectThrow_Z.cpp"),
            Object(NonMatching, "Engine/Rtc_Z.cpp"),
            Object(NonMatching, "Engine/AnimationOmni_Z.cpp"),
            Object(NonMatching, "Engine/KeyframerrVec3f_Z.cpp"),
            Object(NonMatching, "Engine/ManipulatorManager_Z.cpp"),
            Object(NonMatching, "Engine/ObjectsGame_Z.cpp"),
            Object(NonMatching, "Engine/GraphLoad_Z.cpp"),
            Object(NonMatching, "Engine/CameraEngine_Z.cpp"),
            Object(NonMatching, "Engine/ObjectsMoveColl_Z.cpp"),
            Object(NonMatching, "Engine/ABC_AgentReserve.cpp"),
            Object(NonMatching, "Engine/HFogDraw_Z.cpp"),
            Object(Matching,    "Engine/Name_Z.cpp"),
            Object(NonMatching, "Engine/LodCollisionMovingSphere_Z.cpp"),
            Object(NonMatching, "Engine/Sound_Z.cpp"),
            Object(NonMatching, "Engine/Sys_Z.cpp"),
            Object(NonMatching, "Engine/UserDefine_Z.cpp"),
            Object(NonMatching, "Engine/MeshVolume_Z.cpp"),
            Object(NonMatching, "Engine/ObjectMoveCollNode_Z.cpp"),
            Object(NonMatching, "Engine/Renderer_Z.cpp"),
            Object(NonMatching, "Engine/InGameObjectsDraw_Z.cpp"),
            Object(NonMatching, "Engine/ObjectGame_Z.cpp"),
            Object(NonMatching, "Engine/LightLoad_Z.cpp"),
            Object(NonMatching, "Engine/CameraOccluder_Z.cpp"),
            Object(NonMatching, "Engine/SequenceMixAnim_Z.cpp"),
            Object(NonMatching, "Engine/SubLevelVolumeAgent_Z.cpp"),
            Object(NonMatching, "Engine/Tree_Z.cpp"),
            Object(NonMatching, "Engine/LodMoveCollCollectable_Z.cpp"),
            Object(NonMatching, "Engine/AnimationCamera_Z.cpp"),
            Object(NonMatching, "Engine/ObjectsBreakColl_Z.cpp"),
            Object(NonMatching, "Engine/RotShapeCollision_Z.cpp"),
            Object(NonMatching, "Engine/PlayAnim_Z.cpp"),
            Object(NonMatching, "Engine/KeyframerrVec2f_Z.cpp"),
            Object(NonMatching, "Engine/ObjectThrowColl_Z.cpp"),
            Object(NonMatching, "Engine/SubWorldLoad_Z.cpp"),
            Object(NonMatching, "Engine/GraphDraw_Z.cpp"),
            Object(NonMatching, "Engine/SeadIndex_Z.cpp"),
            Object(NonMatching, "Engine/UnSharedCollisionTool_Z.cpp"),
            Object(NonMatching, "Engine/ObjectMove_Z.cpp"),
            Object(NonMatching, "Engine/Menu3DDraw_Z.cpp"),
            Object(NonMatching, "Engine/MeshAABB_Z.cpp"),
            Object(NonMatching, "Engine/DisplayList_Z.cpp"),
            Object(NonMatching, "Engine/MaterialAnimLoad_Z.cpp"),
            Object(NonMatching, "Engine/Console_Z.cpp"),
            Object(NonMatching, "Engine/LowMemory_Z.cpp"),
            Object(NonMatching, "Engine/SelfRunning_Z.cpp"),
            Object(NonMatching, "Engine/BitArray_Z.cpp"),
            Object(NonMatching, "Engine/CameraZone_Z.cpp"),
            Object(Matching,    "Engine/String_Z.cpp"),
            Object(NonMatching, "Engine/StreamManager_Z.cpp"),
            Object(NonMatching, "Engine/GameManagerCmd_Z.cpp"),
            Object(NonMatching, "Engine/Animation_Z.cpp"),
            Object(NonMatching, "Engine/LodMoveCollCling_Z.cpp"),
            Object(NonMatching, "Engine/KeyframerRot_Z.cpp"),
            Object(NonMatching, "Engine/ObjectsBreakCollShadow_Z.cpp"),
            Object(NonMatching, "Engine/ClassManager_Z.cpp"),
            Object(NonMatching, "Engine/Collision_Z.cpp"),
            Object(NonMatching, "Engine/BoneNode_Z.cpp"),
            Object(NonMatching, "Engine/Node_Z.cpp"),
            Object(NonMatching, "Engine/ObjectMoveCollVol_Z.cpp"),
            Object(NonMatching, "Engine/Camera_Z.cpp"),
            Object(NonMatching, "Engine/FlareDraw_Z.cpp"),
            Object(NonMatching, "Engine/ResourceObject_Z.cpp"),
            Object(NonMatching, "Engine/BigFileManager_Z.cpp"),
            Object(NonMatching, "Engine/SkinCollisionMovingSphere_Z.cpp"),
            Object(NonMatching, "Engine/AStar_Z.cpp"),
            Object(NonMatching, "Engine/Ghost_Z.cpp"),
            Object(NonMatching, "Engine/AnimFrameLoad_Z.cpp"),
            Object(NonMatching, "Engine/AnimationLoad_Z.cpp"),
            Object(NonMatching, "Engine/RendererPrimitiveBuffers_Z.cpp"),
            Object(NonMatching, "Engine/WaterHeightmap_Z.cpp"),
            Object(NonMatching, "Engine/Light_Z.cpp"),
            Object(NonMatching, "Engine/AnimFrame_Z.cpp"),
            Object(NonMatching, "Engine/SeadHandle_Z.cpp"),
            Object(NonMatching, "Engine/Menu_Z.cpp"),
            Object(NonMatching, "Engine/MeshCollisionSphere.cpp"),
            Object(NonMatching, "Engine/SkelCollision_Z.cpp"),
            Object(NonMatching, "Engine/ARAM_Z.cpp"),
            Object(NonMatching, "Engine/CollisionVolCollision_Z.cpp"),
            Object(NonMatching, "Engine/SubWorld_Z.cpp"),
            Object(NonMatching, "Engine/Lod_Z.cpp"),
            Object(NonMatching, "Engine/MeshDraw_Z.cpp"),
            Object(NonMatching, "Engine/InGameDatasLoadAscii_Z.cpp"),
            Object(NonMatching, "Engine/ObjectsMove_Z.cpp"),
            Object(NonMatching, "Engine/RotShape_Z.cpp"),
            Object(NonMatching, "Engine/DynamicAnim1_Z.cpp"),
            Object(NonMatching, "Engine/TextureManager_Z.cpp"),
            Object(NonMatching, "Engine/RtcAgent_Z.cpp"),
            Object(NonMatching, "Engine/OccluderCollision_Z.cpp"),
            Object(NonMatching, "Engine/File_Z.cpp"),
            Object(NonMatching, "Engine/SkinLoad_Z.cpp"),
            Object(NonMatching, "Engine/MaterialAnim_Z.cpp"),
            Object(NonMatching, "Engine/Flare_Z.cpp"),
            Object(NonMatching, "Engine/VehiculeMove_Z.cpp"),
            Object(NonMatching, "Engine/RotShapeDraw_Z.cpp"),
            Object(NonMatching, "Engine/Bitmap_Z.cpp"),
            Object(NonMatching, "Engine/AnimatedAgent_Z.cpp"),
            Object(NonMatching, "Engine/ABC_ScriptManager.cpp"),
            Object(NonMatching, "Engine/LodCollisions_Z.cpp"),
            Object(NonMatching, "Engine/Streaming_Z.cpp"),
            Object(NonMatching, "Engine/SurfaceDraw_Z.cpp"),
            Object(NonMatching, "Engine/Error_Z.cpp"),
            Object(NonMatching, "Engine/ClassNameResManager_Z.cpp"),
            Object(NonMatching, "Engine/SoundManager_Z.cpp"),
            Object(NonMatching, "Engine/AnimationManager_Z.cpp"),
            Object(NonMatching, "Engine/InGameObjectsLoadAscii_Z.cpp"),
            Object(NonMatching, "Engine/PopupMenu_Z.cpp"),
            Object(NonMatching, "Engine/SequenceAnim_Z.cpp"),
            Object(NonMatching, "Engine/WorldDraw_Z.cpp"),
            Object(NonMatching, "Engine/LodLoad_Z.cpp"),
            Object(NonMatching, "Engine/Menu2D_Z.cpp"),
            Object(NonMatching, "Engine/Handle_Z.cpp"),
            Object(NonMatching, "Engine/GameRtc_Z.cpp"),
            Object(NonMatching, "Engine/EmiterDraw_Z.cpp"),
            Object(NonMatching, "Engine/AnimationManagerSkel_Z.cpp"),
            Object(NonMatching, "Engine/CameraEngineZoneColl_Z.cpp"),
            Object(NonMatching, "Engine/Breakable_Z.cpp"),
            Object(NonMatching, "Engine/Material_Z.cpp"),
            Object(NonMatching, "Engine/ObjectsGameSkel_Z.cpp"),
            Object(NonMatching, "Engine/DynamicAnim2_Z.cpp"),
            Object(NonMatching, "Engine/Agent_Z.cpp"),
            Object(NonMatching, "Engine/RtcAnimationNode_Z.cpp"),
            Object(NonMatching, "Engine/WorldLoad_Z.cpp"),
            Object(NonMatching, "Engine/CollisionVolLoad_Z.cpp"),
            Object(NonMatching, "Engine/GameObj_Z.cpp"),
            Object(NonMatching, "Engine/Graph_Z.cpp"),
            Object(NonMatching, "Engine/Skin_Z.cpp"),
            Object(NonMatching, "Engine/InputAction_Z.cpp"),
            Object(NonMatching, "Engine/S_MALLOC.cpp"),
            Object(NonMatching, "Engine/SkinCollisionSphere_Z.cpp"),
            Object(NonMatching, "Engine/World_Z.cpp"),
            Object(NonMatching, "Engine/MaterialObj_Z.cpp"),
            Object(NonMatching, "Engine/MaterialManager_Z.cpp"),
            Object(NonMatching, "Engine/TriangleCache_Z.cpp"),
            Object(NonMatching, "Engine/Random_Z.cpp"),
            Object(NonMatching, "Engine/SurfaceLoad_Z.cpp"),
            Object(NonMatching, "Engine/LodMoveCollShadow_Z.cpp"),
            Object(NonMatching, "Engine/GraphLevel_Z.cpp"),
            Object(NonMatching, "Engine/SplineZoneLoad_Z.cpp"),
            Object(NonMatching, "Engine/KeyframerLoad_Z.cpp"),
            Object(NonMatching, "Engine/Main_Z.cpp"),
            Object(NonMatching, "Engine/Object_Z.cpp"),
            Object(NonMatching, "Engine/Menu2DDraw_Z.cpp"),
            Object(NonMatching, "Engine/WarpLoad_Z.cpp"),
            Object(NonMatching, "Engine/ConsoleInterp_Z.cpp"),
            Object(NonMatching, "Engine/RtcLoad_Z.cpp"),
            Object(NonMatching, "Engine/SuperSpray_Z.cpp"),
            Object(NonMatching, "Engine/NetManager_Virtual_Z.cpp"),
            Object(NonMatching, "Engine/OccludedSeadHandle_Z.cpp"),
            Object(NonMatching, "Engine/CameraEngineZone_Z.cpp"),
            Object(NonMatching, "Engine/ObjectCollisionTools_Z.cpp"),
            Object(NonMatching, "Engine/ABC_AgentMessage.cpp"),
            Object(NonMatching, "Engine/Fonts_Z.cpp"),
            Object(NonMatching, "Engine/PlayParticles_Z.cpp"),
            Object(NonMatching, "Engine/NetManager_Z.cpp"),
            Object(NonMatching, "Engine/AnimationMesh_Z.cpp"),
            Object(NonMatching, "Engine/CollisionVol_Z.cpp"),
            Object(NonMatching, "Engine/LodCollision_Z.cpp"),
            Object(NonMatching, "Engine/RtcPlayer_Z.cpp"),
            Object(NonMatching, "Engine/ABC_Behavior.cpp"),
            Object(NonMatching, "Engine/UnPack_Z.cpp"),
            Object(Matching,    "Engine/Assert_Z.cpp"),
            Object(NonMatching, "Engine/CameraStream_Z.cpp"),
            Object(NonMatching, "Engine/DebugTools_Z.cpp"),
            Object(NonMatching, "Engine/SurfaceCling_Z.cpp"),
            Object(NonMatching, "Engine/KeyframerU32_Z.cpp"),
            Object(NonMatching, "Engine/HFogLoad_Z.cpp"),
            Object(NonMatching, "Engine/LodMoveCollNode_Z.cpp"),
            Object(NonMatching, "Engine/KeyframerHdl_Z.cpp"),
            Object(NonMatching, "Engine/NodeLoad_Z.cpp"),
            Object(NonMatching, "Engine/MaterialLoad_Z.cpp"),
            Object(NonMatching, "Engine/SplineZoneDraw_Z.cpp"),
            Object(NonMatching, "Engine/CollisionTool_Z.cpp"),
            Object(NonMatching, "Engine/KeyframerVec4f_Z.cpp"),
            Object(NonMatching, "Engine/UnSharedObjectCollisionTools_Z.cpp"),
            Object(NonMatching, "Engine/SurfaceCollisionMovingSphere_Z.cpp"),
            Object(NonMatching, "Engine/AnimationManagerMes_Z.cpp"),
            Object(NonMatching, "Engine/GameAgent_Z.cpp"),
            Object(NonMatching, "Engine/AnimMessage_Z.cpp"),
            Object(NonMatching, "Engine/Omni_Z.cpp"),
            Object(NonMatching, "Engine/LodCollisionSphere_Z.cpp"),
            Object(NonMatching, "Engine/ABC_ScriptManagerReserve_Z.cpp"),
            Object(NonMatching, "Engine/ObjectsMoveCollNode_Z.cpp"),
            Object(NonMatching, "Engine/LodDynAgent_Z.cpp"),
            Object(NonMatching, "Engine/LodMoveCollCarrying_Z.cpp"),
            Object(NonMatching, "Engine/Particles_Z.cpp"),
            Object(NonMatching, "Engine/AnimationNode_Z.cpp"),
            Object(NonMatching, "Engine/Throwable_Z.cpp"),
            Object(NonMatching, "Engine/FontsDraw_Z.cpp"),
            Object(NonMatching, "Engine/Menu2DLoadAscii_Z.cpp"),
            Object(NonMatching, "Engine/NetDataSet_Z.cpp"),
            Object(NonMatching, "Engine/Mesh_Z.cpp"),
            Object(NonMatching, "Engine/CameraDraw_Z.cpp"),
            Object(NonMatching, "Engine/Timer_Z.cpp"),
            Object(NonMatching, "Engine/Spline_Z.cpp"),
            Object(NonMatching, "Engine/ConsoleMessage_Z.cpp"),
            Object(NonMatching, "Engine/Skel_Z.cpp"),
            Object(NonMatching, "Engine/MeshMorph_Z.cpp"),
            Object(NonMatching, "Engine/SplineZone_Z.cpp"),
            Object(NonMatching, "Engine/ParticlesDraw_Z.cpp"),
            Object(NonMatching, "Engine/VolumeAgent_Z.cpp"),
            Object(NonMatching, "Engine/Dupe/String_Z.c"),
        ],
    },
    {
        "lib": "LibGC",
        "mw_version": config.linker_version,
        "cflags": cflags_rat_base,
        "progress_category": "libgc",  # str | List[str]
        "objects": [
            Object(NonMatching, "LibGC/MeshGCDraw_Z.cpp"),
            Object(NonMatching, "LibGC/GCConsoleSystem_Z.cpp"),
            Object(NonMatching, "LibGC/SurfaceGC_Z.cpp"),
            Object(NonMatching, "LibGC/SystemObjectGC_Z.cpp"),
            Object(NonMatching, "LibGC/GCRenderer3D_Z.cpp"),
            Object(NonMatching, "LibGC/GCMovieManipulator_Z.cpp"),
            Object(NonMatching, "LibGC/SkinGCDraw_Z.cpp"),
            Object(NonMatching, "LibGC/SkelGC_Z.cpp"),
            Object(NonMatching, "LibGC/FlareGC_Z.cpp"),
            Object(NonMatching, "LibGC/GCSound_Z.cpp"),
            Object(NonMatching, "LibGC/InGameObjectsGC_Z.cpp"),
            Object(NonMatching, "LibGC/WarpGC_Z.cpp"),
            Object(NonMatching, "LibGC/RotShapeGC_Z.cpp"),
            Object(NonMatching, "LibGC/ParticlesGC_Z.cpp"),
            Object(NonMatching, "LibGC/RotShapeGCDraw_Z.cpp"),
            Object(NonMatching, "LibGC/GCMcManager_Z.cpp"),
            Object(NonMatching, "LibGC/FlareGCDraw_Z.cpp"),
            Object(NonMatching, "LibGC/GCRendererTransp_Z.cpp"),
            Object(NonMatching, "LibGC/GCFile_Z.cpp"),
            Object(NonMatching, "LibGC/MaterialGC_Z.cpp"),
            Object(NonMatching, "LibGC/LodGC_Z.cpp"),
            Object(NonMatching, "LibGC/MathGC_Z.cpp"),
            Object(NonMatching, "LibGC/GCDrawString.cpp"),
            Object(NonMatching, "LibGC/GCRendererLighting_Z.cpp"),
            Object(NonMatching, "LibGC/LodGCDraw_Z.cpp"),
            Object(NonMatching, "LibGC/ParticlesGCDraw_Z.cpp"),
            Object(NonMatching, "LibGC/GCFrustrum_Z.cpp"),
            Object(NonMatching, "LibGC/GCStreamManager_Z.cpp"),
            Object(NonMatching, "LibGC/GCSoundManager_Z.cpp"),
            Object(NonMatching, "LibGC/MeshGC_Z.cpp"),
            Object(NonMatching, "LibGC/SurfaceGCDraw_Z.cpp"),
            Object(NonMatching, "LibGC/GCRendererDraw_Z.cpp"),
            Object(NonMatching, "LibGC/GCSndStream_Z.cpp"),
            Object(NonMatching, "LibGC/GCRenderer_Z.cpp"),
            Object(NonMatching, "LibGC/GCConsole_Z.cpp"),
            Object(NonMatching, "LibGC/WarpGCDraw_Z.cpp"),
            Object(NonMatching, "LibGC/GCSoundStreaming_Z.cpp"),
            Object(NonMatching, "LibGC/SkinGC_Z.cpp"),
            Object(NonMatching, "LibGC/GCInput_Z.cpp"),
            Object(NonMatching, "LibGC/GCSoundBF.cpp"),
            Object(NonMatching, "LibGC/GCMovie_Z.cpp"),
            Object(NonMatching, "LibGC/GCMain_Z.cpp"),
            Object(NonMatching, "LibGC/GCConsoleFolder_Z.cpp"),
            Object(NonMatching, "LibGC/GCRenderer2D_Z.cpp"),
            Object(NonMatching, "LibGC/SurfaceGCCache_Z.cpp"),
            Object(NonMatching, "LibGC/wiitextures.c"),
        ],
    },
    {
        "lib": "Game",
        "mw_version": config.linker_version,
        "cflags": cflags_rat_base,
        "progress_category": "game",  # str | List[str]
        "objects": [
            Object(NonMatching, "Rat/Mission_Heist.cpp"),
            Object(NonMatching, "Rat/Mission_LinguiniMaking.cpp"),
            Object(NonMatching, "Rat/MenuManager_G.cpp"),
            Object(NonMatching, "Rat/CameraGame_G.cpp"),
            Object(NonMatching, "Rat/IsToBePlayed.cpp"),
            Object(NonMatching, "Rat/CreatureDeaths.cpp"),
            Object(NonMatching, "Rat/CreaturesBallMoveStates_G.cpp"),
            Object(NonMatching, "Rat/DummyGen.cpp"),
            Object(NonMatching, "Rat/CreatureFightStates_G.cpp"),
            Object(NonMatching, "Rat/BriefInfo.cpp"),
            Object(NonMatching, "Rat/Mission_Dream.cpp"),
            Object(NonMatching, "Rat/Mission_CookingPlateInterface.cpp"),
            Object(NonMatching, "Rat/PlayerMove_G.cpp"),
            Object(NonMatching, "Rat/Menu3DScenery.cpp"),
            Object(NonMatching, "Rat/VolumeDelayedStart_G.cpp"),
            Object(NonMatching, "Rat/Mission_Wii_Fish.cpp"),
            Object(NonMatching, "Rat/LogicAgent_G.cpp"),
            Object(NonMatching, "Rat/Mission_CollectTrigger.cpp"),
            Object(NonMatching, "Rat/GameMgr_G.cpp"),
            Object(NonMatching, "Rat/CreatureImpactStates_G.cpp"),
            Object(NonMatching, "Rat/IT_CarryingMove.cpp"),
            Object(NonMatching, "Rat/CharsData_G.cpp"),
            Object(NonMatching, "Rat/LoadingDraw_G.cpp"),
            Object(NonMatching, "Rat/IT_DYNOBJMove_G.cpp"),
            Object(NonMatching, "Rat/CreaturesWaitStates_G.cpp"),
            Object(NonMatching, "Rat/Mission_Wii_Wash.cpp"),
            Object(NonMatching, "Rat/FriendsMove_G.cpp"),
            Object(NonMatching, "Rat/InGameSounds_G.cpp"),
            Object(NonMatching, "Rat/CreaturesSwim_G.cpp"),
            Object(NonMatching, "Rat/Heros_G.cpp"),
            Object(NonMatching, "Rat/CreaturesPoleStates_G.cpp"),
            Object(NonMatching, "Rat/Shop.cpp"),
            Object(NonMatching, "Rat/ActionHelper_G.cpp"),
            Object(NonMatching, "Rat/CreaturesBoneManip.cpp"),
            Object(NonMatching, "Rat/InGameCreatures_G.cpp"),
            Object(NonMatching, "Rat/ObjectAgent_G.cpp"),
            Object(NonMatching, "Rat/MenuKeys.cpp"),
            Object(NonMatching, "Rat/StreamGameAgent_G.cpp"),
            Object(NonMatching, "Rat/Dialogs_Extras.cpp"),
            Object(NonMatching, "Rat/Mission_Goto.cpp"),
            Object(NonMatching, "Rat/IT_BallWalk_G.cpp"),
            Object(NonMatching, "Rat/BaseInGame3D.cpp"),
            Object(NonMatching, "Rat/ItemMgr_G.cpp"),
            Object(NonMatching, "Rat/PhysicObj_G.cpp"),
            Object(NonMatching, "Rat/InGamePlayerPages_G.cpp"),
            Object(NonMatching, "Rat/CreaturesStates_G.cpp"),
            Object(NonMatching, "Rat/Mission_Wii_CrepeInterface.cpp"),
            Object(NonMatching, "Rat/Frame_G.cpp"),
            Object(NonMatching, "Rat/CreatureStatic.cpp"),
            Object(NonMatching, "Rat/LiquidFlow_G.cpp"),
            Object(NonMatching, "Rat/Mission_Multi_Collect.cpp"),
            Object(NonMatching, "Rat/MissionTemplate_G.cpp"),
            Object(NonMatching, "Rat/CreatureGlissade.cpp"),
            Object(NonMatching, "Rat/Game_SoundMgr_G.cpp"),
            Object(NonMatching, "Rat/CreatureSkid.cpp"),
            Object(NonMatching, "Rat/Mission_CuttingPotatoes.cpp"),
            Object(NonMatching, "Rat/CreatureControlPanel.cpp"),
            Object(NonMatching, "Rat/CreaturesPushButtonStates_G.cpp"),
            Object(NonMatching, "Rat/CreatureRat_G.cpp"),
            Object(NonMatching, "Rat/EvenementVolAgent_G.cpp"),
            Object(NonMatching, "Rat/Mission_ControlPanel.cpp"),
            Object(NonMatching, "Rat/MenuLogicAgent_G.cpp"),
            Object(NonMatching, "Rat/GusteauMove.cpp"),
            Object(NonMatching, "Rat/VibrationManager_G.cpp"),
            Object(NonMatching, "Rat/CameraAgent_G.cpp"),
            Object(NonMatching, "Rat/CreatureSemaphore.cpp"),
            Object(NonMatching, "Rat/IT_Switch.cpp"),
            Object(NonMatching, "Rat/Mission_CookingSoupInterfaceYesNo.cpp"),
            Object(NonMatching, "Rat/Mission_Colony.cpp"),
            Object(NonMatching, "Rat/Mission_WireConnect.cpp"),
            Object(NonMatching, "Rat/CreatureBumper.cpp"),
            Object(NonMatching, "Rat/Mission_LinguiniMakingInterface.cpp"),
            Object(NonMatching, "Rat/ScriptExternalCommands_G.cpp"),
            Object(NonMatching, "Rat/TextGameDraw_G.cpp"),
            Object(NonMatching, "Rat/FlyUpVolumeAgent_G.cpp"),
            Object(NonMatching, "Rat/IT_FishMove.cpp"),
            Object(NonMatching, "Rat/LevelManipulator_G.cpp"),
            Object(NonMatching, "Rat/CameraEdited.cpp"),
            Object(NonMatching, "Rat/Smell_G.cpp"),
            Object(NonMatching, "Rat/PhysicColl_G.cpp"),
            Object(NonMatching, "Rat/EnemyGenerator_G.cpp"),
            Object(NonMatching, "Rat/Mission_CookingLinguiniInterface.cpp"),
            Object(NonMatching, "Rat/Config_G.cpp"),
            Object(NonMatching, "Rat/BaseInGameDatas_G.cpp"),
            Object(NonMatching, "Rat/CreaturePST_TOOLS_G.cpp"),
            Object(NonMatching, "Rat/InGamePlayer_G.cpp"),
            Object(NonMatching, "Rat/ResName.cpp"),
            Object(NonMatching, "Rat/Dialogs_LoadSave.cpp"),
            Object(NonMatching, "Rat/LightVolumeAgent_G.cpp"),
            Object(NonMatching, "Rat/Mission_MiniGame.cpp"),
            Object(NonMatching, "Rat/CreaturesManager_G.cpp"),
            Object(NonMatching, "Rat/RtcScriptAgent_G.cpp"),
            Object(NonMatching, "Rat/Mission_Wii_WashInterface.cpp"),
            Object(NonMatching, "Rat/CreatureFishing.cpp"),
            Object(NonMatching, "Rat/IT_Fish_G.cpp"),
            Object(NonMatching, "Rat/MultiMapLevel.cpp"),
            Object(NonMatching, "Rat/GuardAgent_G.cpp"),
            Object(NonMatching, "Rat/DialogGroup_G.cpp"),
            Object(NonMatching, "Rat/WanderingPath_G.cpp"),
            Object(NonMatching, "Rat/GangAgent_G.cpp"),
            Object(NonMatching, "Rat/FootPrints_G.cpp"),
            Object(NonMatching, "Rat/AutoCompletion_G.cpp"),
            Object(NonMatching, "Rat/ThrownMove_G.cpp"),
            Object(NonMatching, "Rat/Mission_MutliTemplate_G.cpp"),
            Object(NonMatching, "Rat/Mission_WireConnectInterface.cpp"),
            Object(NonMatching, "Rat/Mission_CuttingPotatoesInterface.cpp"),
            Object(NonMatching, "Rat/ChangeLevelVolumeAgent_G.cpp"),
            Object(NonMatching, "Rat/Friends_G.cpp"),
            Object(NonMatching, "Rat/Dialogs_System.cpp"),
            Object(NonMatching, "Rat/ScriptExternals_G.cpp"),
            Object(NonMatching, "Rat/LevelAdvancement_G.cpp"),
            Object(NonMatching, "Rat/Ropes_G.cpp"),
            Object(NonMatching, "Rat/Mission_Mutli_Rope.cpp"),
            Object(NonMatching, "Rat/Mission_CookingSoupYesNo.cpp"),
            Object(NonMatching, "Rat/CreaturesDashStates_G.cpp"),
            Object(NonMatching, "Rat/Mission_Collect.cpp"),
            Object(NonMatching, "Rat/BaseAgent_G.cpp"),
            Object(NonMatching, "Rat/UnLock_G.cpp"),
            Object(NonMatching, "Rat/CollectAgent_G.cpp"),
            Object(NonMatching, "Rat/Mission_Chase.cpp"),
            Object(NonMatching, "Rat/IT_SOUND_G.CPP"),
            Object(NonMatching, "Rat/ScriptManagerRtcScript_G.cpp"),
            Object(NonMatching, "Rat/Mission_CookinCakeInterface.cpp"),
            Object(NonMatching, "Rat/PhysicWorld_G.cpp"),
            Object(NonMatching, "Rat/IT_DYNOBJ_G.cpp"),
            Object(NonMatching, "Rat/MissionVolumeAgent_G.cpp"),
            Object(NonMatching, "Rat/ScriptManager_G.cpp"),
            Object(NonMatching, "Rat/PermanentDraw.cpp"),
            Object(NonMatching, "Rat/CreatureVehiculeStates_G.cpp"),
            Object(NonMatching, "Rat/CreaturesWallClimbStates.cpp"),
            Object(NonMatching, "Rat/Dialogs_Pause.cpp"),
            Object(NonMatching, "Rat/Mission_Multi_Collect_Interface.cpp"),
            Object(NonMatching, "Rat/EndMissionVolumeAgent_G.cpp"),
            Object(NonMatching, "Rat/VibrationKeyframers_G.cpp"),
            Object(NonMatching, "Rat/HumanHideVolumeAgent_G.cpp"),
            Object(NonMatching, "Rat/Dialogs_MisssionEnd.cpp"),
            Object(NonMatching, "Rat/UserCommand_G.cpp"),
            Object(NonMatching, "Rat/CreaturesJumpStates_G.cpp"),
            Object(NonMatching, "Rat/MenuTools.cpp"),
            Object(NonMatching, "Rat/SaveVolumeAgent_G.cpp"),
            Object(NonMatching, "Rat/GroupTriggerZone_G.cpp"),
            Object(NonMatching, "Rat/BaseInGameDatas_Text_G.cpp"),
            Object(NonMatching, "Rat/Mission_Multi_Race.cpp"),
            Object(NonMatching, "Rat/Mission_Wii_Crepe.cpp"),
            Object(NonMatching, "Rat/InGameFX_G.cpp"),
            Object(NonMatching, "Rat/CheckpointVolAgent_G.cpp"),
            Object(NonMatching, "Rat/MissionManager_G.cpp"),
            Object(NonMatching, "Rat/CreaturesEnemiesStates_G.cpp"),
            Object(NonMatching, "Rat/Mission_ShootTarget.cpp"),
            Object(NonMatching, "Rat/RtcScripted_G.cpp"),
            Object(NonMatching, "Rat/Mission_Multi_Ball_Interface.cpp"),
            Object(NonMatching, "Rat/NodeVolumeAgent_G.cpp"),
            Object(NonMatching, "Rat/Mission_CookingSoup.cpp"),
            Object(NonMatching, "Rat/Mission_Mutli_Race_Interface.cpp"),
            Object(NonMatching, "Rat/MemoryCardMgr_G.cpp"),
            Object(NonMatching, "Rat/PersoLight_G.cpp"),
            Object(NonMatching, "Rat/ConditionVolumeAgent_G.cpp"),
            Object(NonMatching, "Rat/IT_BallWalkMove_G.cpp"),
            Object(NonMatching, "Rat/CameraChase.cpp"),
            Object(NonMatching, "Rat/IT_LinkObj.cpp"),
            Object(NonMatching, "Rat/BaseInGameItems_G.cpp"),
            Object(NonMatching, "Rat/CreaturePointJump.cpp"),
            Object(NonMatching, "Rat/Dialogs_Common.cpp"),
            Object(NonMatching, "Rat/CameraTools.cpp"),
            Object(NonMatching, "Rat/FXVolumeAgent_G.cpp"),
            Object(NonMatching, "Rat/Mission_Switch.cpp"),
            Object(NonMatching, "Rat/Game_ParticleMgr_G.cpp"),
            Object(NonMatching, "Rat/ProGounrMgr_G.cpp"),
            Object(NonMatching, "Rat/CreatureSticky.cpp"),
            Object(NonMatching, "Rat/IT_Condition.cpp"),
            Object(NonMatching, "Rat/IT_Break.cpp"),
            Object(NonMatching, "Rat/CreaturesMove_G.cpp"),
            Object(NonMatching, "Rat/Dialog_MC_Base.cpp"),
            Object(NonMatching, "Rat/Mission_Semaphore.cpp"),
            Object(NonMatching, "Rat/CreatureShootTarget.cpp"),
            Object(NonMatching, "Rat/GuardMove_G.cpp"),
            Object(NonMatching, "Rat/Player_G.cpp"),
            Object(NonMatching, "Rat/ScriptManagerEngine_G.cpp"),
            Object(NonMatching, "Rat/IT_BallMove_G.cpp"),
            Object(NonMatching, "Rat/ZoneVolumeAgent_G.cpp"),
            Object(NonMatching, "Rat/MenuStyle.cpp"),
            Object(NonMatching, "Rat/LangDefine.cpp"),
            Object(NonMatching, "Rat/GroupAgent_G.cpp"),
            Object(NonMatching, "Rat/GusteauAgent.cpp"),
            Object(NonMatching, "Rat/CreaturesGrabStates_G.cpp"),
            Object(NonMatching, "Rat/Mission_Multi_Rope_Interface.cpp"),
            Object(NonMatching, "Rat/LevelData_G.cpp"),
            Object(NonMatching, "Rat/Mission_CookingSoupInterface.cpp"),
            Object(NonMatching, "Rat/Mission_CookingLinguini.cpp"),
            Object(NonMatching, "Rat/DetectVolumeAgent_G.cpp"),
            Object(NonMatching, "Rat/Mission_Glissade.cpp"),
            Object(NonMatching, "Rat/DialogVoices.cpp"),
            Object(NonMatching, "Rat/GameLogicAgent_G.cpp"),
            Object(NonMatching, "Rat/MenuParser.cpp"),
            Object(NonMatching, "Rat/RtcScriptFunctions_G.cpp"),
            Object(NonMatching, "Rat/PaddleChecker_G.cpp"),
            Object(NonMatching, "Rat/CreaturesMachineCommands_G.cpp"),
            Object(NonMatching, "Rat/IT_Bumper.cpp"),
            Object(NonMatching, "Rat/ImpactVolumeAgent_G.cpp"),
            Object(NonMatching, "Rat/MusicManager_G.cpp"),
            Object(NonMatching, "Rat/Mission_Wii_FishInterface.cpp"),
            Object(NonMatching, "Rat/Mission_Tutorial.cpp"),
            Object(NonMatching, "Rat/MainGame_G.cpp"),
            Object(NonMatching, "Rat/InGamePlayerGarfield_G.cpp"),
            Object(NonMatching, "Rat/Dialogs_MainMenu.cpp"),
            Object(NonMatching, "Rat/CreatureCarry.cpp"),
            Object(NonMatching, "Rat/LevelAgent_G.cpp"),
            Object(NonMatching, "Rat/GlobalInGameDatas_G.cpp"),
            Object(NonMatching, "Rat/Purchase.cpp"),
            Object(NonMatching, "Rat/Creatures_G.cpp"),
            Object(NonMatching, "Rat/Dialog_G.cpp"),
            Object(NonMatching, "Rat/CreatureRatBeamRun.cpp"),
            Object(NonMatching, "Rat/CreatureRatRope.cpp"),
            Object(NonMatching, "Rat/Mission_CookingPlate.cpp"),
            Object(NonMatching, "Rat/V_RaftMove.cpp"),
            Object(NonMatching, "Rat/LevelMenu_G.cpp"),
            Object(NonMatching, "Rat/IT_Ball_G.cpp"),
            Object(NonMatching, "Rat/Mission_Multi_Ball.cpp"),
            Object(NonMatching, "Rat/Mission_CookingCake.cpp"),
            Object(NonMatching, "Rat/Mission_TimeCount.cpp"),
            Object(NonMatching, "Rat/CameraFog_G.cpp"),
            Object(NonMatching, "Rat/PhysicAgt_G.cpp"),
            Object(NonMatching, "Rat/Mission_PushButtonInterface.cpp"),
            Object(NonMatching, "Rat/Mission_PushButton.cpp"),
            Object(NonMatching, "Rat/Enemies_G.cpp"),
            Object(NonMatching, "Rat/Button_G.cpp"),
            Object(NonMatching, "Rat/IT_Stone_G.cpp"),
            Object(NonMatching, "Rat/GroupMove_G.cpp"),
            Object(NonMatching, "Rat/IT_BreakMove.cpp"),
            Object(NonMatching, "Rat/Mission_PushLift.cpp"),
            Object(NonMatching, "Rat/CreaturesCommands_G.cpp"),
            Object(NonMatching, "Rat/InGamePlayer_Draw_G.cpp"),
            Object(NonMatching, "Rat/V_Raft.cpp"),
            Object(NonMatching, "Rat/IT_Carrying.cpp"),
            Object(NonMatching, "Rat/InputDef_G.cpp"),
            Object(NonMatching, "Rat/Mission_Global.cpp"),
            Object(NonMatching, "Rat/CameraRTC.cpp"),
            Object(NonMatching, "Rat/Mission_Raft.cpp"),
            Object(NonMatching, "Rat/IT_LinkObjMove.cpp"),
            Object(NonMatching, "Rat/IT_CollectMove_G.cpp"),
            Object(NonMatching, "Rat/PointJump_G.cpp"),
            Object(NonMatching, "Rat/LogicLevel.cpp"),
            Object(NonMatching, "Rat/MissionInfo_G.cpp"),
            Object(NonMatching, "Rat/Mission_PreLinguiniMaking.cpp"),
            Object(NonMatching, "Rat/CreatureOtherStates_G.cpp"),
            Object(NonMatching, "Rat/CreatureFlying.cpp"),
            Object(NonMatching, "Rat/VolumeDelayedStartMove_G.cpp"),
            Object(NonMatching, "Rat/Mission_Container.cpp"),
            Object(NonMatching, "Rat/Mission_GlissadeInterface.cpp"),
        ],
    },
]


# Optional callback to adjust link order. This can be used to add, remove, or reorder objects.
# This is called once per module, with the module ID and the current link order.
#
# For example, this adds "dummy.c" to the end of the DOL link order if configured with --non-matching.
# "dummy.c" *must* be configured as a Matching (or Equivalent) object in order to be linked.
def link_order_callback(module_id: int, objects: List[str]) -> List[str]:
    # Don't modify the link order for matching builds
    if not config.non_matching:
        return objects
    if module_id == 0:  # DOL
        return objects + ["dummy.c"]
    return objects

# Uncomment to enable the link order callback.
# config.link_order_callback = link_order_callback


# Optional extra categories for progress tracking
# Adjust as desired for your project
config.progress_categories = [
    ProgressCategory("game", "Game Code"),
    ProgressCategory("engine", "Engine Code"),
    ProgressCategory("libgc", "LibGC Code"),
    ProgressCategory("sdk", "SDK Code"),
]
config.progress_each_module = args.verbose

if args.mode == "configure":
    # Write build.ninja and objdiff.json
    generate_build(config)
elif args.mode == "progress":
    # Print progress and write progress.json
    calculate_progress(config)
else:
    sys.exit("Unknown mode: " + args.mode)
